stages:
    - build
    - backendTest
    - frontendTest
  
build:
    stage: build
    image: node
    script:
      - cd ./src/lastmanstanding 
      - echo "Start building App"
      - npm install
      - npm build
      - echo "Build successfully!"
  
backendTest:
    stage: backendTest
    image: python3
    script:
      - cd ./src/lastmanstanding/tests
      - echo "Testing Backend"
      - pip install boto3 moto pytest
      - pytest test_adminActions.py
      - pytest test_getLeagueInfo.py
      - pytest test_getPremInfo.py
      - pytest test_teamInfo.py
      - pytest test_teamSelection.py
      - echo "Backend tested successfully!"

frontendTest:
    stage: frontendTest
    image: node
    script:
      - cd ./src/lastmanstanding
      - echo "Testing Frontend"
      - npm install
      - rm -rf node_modules/eslint
      - CI=true npm test
      - echo "Frontend tested successfully!"