stages:
    - build
    - backendTest
    - frontendTest
  
build:
    stage: build
    image: node
    script:
      - cd ./src/lastmanstanding 
      - echo "Start building App"
      - npm install
      - npm build
      - echo "Build successfully!"
  
backendTest:
    stage: backendTest
    image: python
    script:
      - cd ./src
      - echo "Setting up virtual env"
      - python3 -m venv venv
      - source venv/bin/activate
      - cd lastmanstanding
      - pip install -r requirements.txt
      - pip install --upgrade pip
      - echo "Testing Backend"
      - PYTHONPATH=:$(echo $PWD) python -m pytest -s
      - echo "Backend tested successfully!"

frontendTest:
    stage: frontendTest
    image: node
    script:
      - cd ./src/lastmanstanding
      - echo "Testing Frontend"
      - npm install
      - rm -rf node_modules/eslint
      - CI=true npm test
      - echo "Frontend tested successfully!"